apiVersion: apps/v1
kind: Deployment
metadata:
  name: bandicoot-staging
  labels:
    version: "2"
    app: "bandicoot"
    env: "staging"
spec:
  replicas: 1
  selector:
    matchLabels:
      run: bandicoot-staging
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: bandicoot-staging
    spec:
      containers:
        - name: bandicoot-staging
          image: gcr.io/kuar-demo/kuard-amd64:green
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          resources:
            requests:
              cpu: "10m"
              memory: "2Mi"
            limits:
              cpu: "100m"
              memory: "5Mi"
          livenessProbe:
            httpGet:
              path: /healthy
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 1
            periodSeconds: 10
            failureThreshold: 3
      restartPolicy: Always
      schedulerName: default-scheduler
      dnsPolicy: ClusterFirst
      securityContext: {}
      terminationGracePeriodSeconds: 5
