apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"ClusterRoleBinding","metadata":{"annotations":{},"name":"contour"},"roleRef":{"apiGroup":"rbac.authorization.k8s.io","kind":"ClusterRole","name":"contour"},"subjects":[{"kind":"ServiceAccount","name":"contour","namespace":"projectcontour"}]}
  creationTimestamp: "2024-11-25T18:52:52Z"
  name: contour
  resourceVersion: "134067"
  uid: 4347c7bc-2bc4-407d-a832-87835cc120a4
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: contour
subjects:
- kind: ServiceAccount
  name: contour
  namespace: projectcontour
