apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"ClusterRole","metadata":{"annotations":{},"name":"contour"},"rules":[{"apiGroups":[""],"resources":["configmaps","endpoints","namespaces","secrets","services"],"verbs":["get","list","watch"]},{"apiGroups":["discovery.k8s.io"],"resources":["endpointslices"],"verbs":["get","list","watch"]},{"apiGroups":["gateway.networking.k8s.io"],"resources":["backendtlspolicies","gatewayclasses","gateways","grpcroutes","httproutes","referencegrants","tcproutes","tlsroutes"],"verbs":["get","list","watch"]},{"apiGroups":["gateway.networking.k8s.io"],"resources":["backendtlspolicies/status","gatewayclasses/status","gateways/status","grpcroutes/status","httproutes/status","tcproutes/status","tlsroutes/status"],"verbs":["update"]},{"apiGroups":["networking.k8s.io"],"resources":["ingresses"],"verbs":["get","list","watch"]},{"apiGroups":["networking.k8s.io"],"resources":["ingresses/status"],"verbs":["create","get","update"]},{"apiGroups":["projectcontour.io"],"resources":["contourconfigurations","extensionservices","httpproxies","tlscertificatedelegations"],"verbs":["get","list","watch"]},{"apiGroups":["projectcontour.io"],"resources":["contourconfigurations/status","extensionservices/status","httpproxies/status"],"verbs":["create","get","update"]}]}
  creationTimestamp: "2024-11-25T18:52:52Z"
  name: contour
  resourceVersion: "134072"
  uid: 3955e912-abca-4aa9-8183-384209aad433
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - endpoints
  - namespaces
  - secrets
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - discovery.k8s.io
  resources:
  - endpointslices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - backendtlspolicies
  - gatewayclasses
  - gateways
  - grpcroutes
  - httproutes
  - referencegrants
  - tcproutes
  - tlsroutes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - backendtlspolicies/status
  - gatewayclasses/status
  - gateways/status
  - grpcroutes/status
  - httproutes/status
  - tcproutes/status
  - tlsroutes/status
  verbs:
  - update
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses/status
  verbs:
  - create
  - get
  - update
- apiGroups:
  - projectcontour.io
  resources:
  - contourconfigurations
  - extensionservices
  - httpproxies
  - tlscertificatedelegations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - projectcontour.io
  resources:
  - contourconfigurations/status
  - extensionservices/status
  - httpproxies/status
  verbs:
  - create
  - get
  - update
