apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    deprecated.daemonset.template.generation: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"DaemonSet","metadata":{"annotations":{},"labels":{"app":"envoy"},"name":"envoy","namespace":"projectcontour"},"spec":{"selector":{"matchLabels":{"app":"envoy"}},"template":{"metadata":{"labels":{"app":"envoy"}},"spec":{"automountServiceAccountToken":false,"containers":[{"args":["envoy","shutdown-manager"],"command":["/bin/contour"],"image":"ghcr.io/projectcontour/contour:v1.30.1","imagePullPolicy":"IfNotPresent","lifecycle":{"preStop":{"exec":{"command":["/bin/contour","envoy","shutdown"]}}},"name":"shutdown-manager","volumeMounts":[{"mountPath":"/admin","name":"envoy-admin"}]},{"args":["-c","/config/envoy.json","--service-cluster $(CONTOUR_NAMESPACE)","--service-node $(ENVOY_POD_NAME)","--log-level info"],"command":["envoy"],"env":[{"name":"CONTOUR_NAMESPACE","valueFrom":{"fieldRef":{"apiVersion":"v1","fieldPath":"metadata.namespace"}}},{"name":"ENVOY_POD_NAME","valueFrom":{"fieldRef":{"apiVersion":"v1","fieldPath":"metadata.name"}}}],"image":"docker.io/envoyproxy/envoy:v1.31.3","imagePullPolicy":"IfNotPresent","lifecycle":{"preStop":{"httpGet":{"path":"/shutdown","port":8090,"scheme":"HTTP"}}},"name":"envoy","ports":[{"containerPort":8080,"hostPort":80,"name":"http","protocol":"TCP"},{"containerPort":8443,"hostPort":443,"name":"https","protocol":"TCP"},{"containerPort":8002,"hostPort":8002,"name":"metrics","protocol":"TCP"}],"readinessProbe":{"httpGet":{"path":"/ready","port":8002},"initialDelaySeconds":3,"periodSeconds":4},"volumeMounts":[{"mountPath":"/config","name":"envoy-config","readOnly":true},{"mountPath":"/certs","name":"envoycert","readOnly":true},{"mountPath":"/admin","name":"envoy-admin"}]}],"initContainers":[{"args":["bootstrap","/config/envoy.json","--xds-address=contour","--xds-port=8001","--xds-resource-version=v3","--resources-dir=/config/resources","--envoy-cafile=/certs/ca.crt","--envoy-cert-file=/certs/tls.crt","--envoy-key-file=/certs/tls.key"],"command":["contour"],"env":[{"name":"CONTOUR_NAMESPACE","valueFrom":{"fieldRef":{"fieldPath":"metadata.namespace"}}}],"image":"ghcr.io/projectcontour/contour:v1.30.1","imagePullPolicy":"IfNotPresent","name":"envoy-initconfig","volumeMounts":[{"mountPath":"/config","name":"envoy-config"},{"mountPath":"/certs","name":"envoycert","readOnly":true}]}],"restartPolicy":"Always","securityContext":{"runAsGroup":65534,"runAsNonRoot":true,"runAsUser":65534},"serviceAccountName":"envoy","terminationGracePeriodSeconds":300,"volumes":[{"emptyDir":{},"name":"envoy-admin"},{"emptyDir":{},"name":"envoy-config"},{"name":"envoycert","secret":{"secretName":"envoycert"}}]}},"updateStrategy":{"rollingUpdate":{"maxUnavailable":"10%"},"type":"RollingUpdate"}}}
  creationTimestamp: "2024-11-25T18:52:52Z"
  generation: 1
  labels:
    app: envoy
  name: envoy
  namespace: projectcontour
  resourceVersion: "134212"
  uid: 0648f7d7-d558-414d-ba9f-3893ca45f3fb
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: envoy
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: envoy
    spec:
      automountServiceAccountToken: false
      containers:
      - args:
        - envoy
        - shutdown-manager
        command:
        - /bin/contour
        image: ghcr.io/projectcontour/contour:v1.30.1
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/contour
              - envoy
              - shutdown
        name: shutdown-manager
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /admin
          name: envoy-admin
      - args:
        - -c
        - /config/envoy.json
        - --service-cluster $(CONTOUR_NAMESPACE)
        - --service-node $(ENVOY_POD_NAME)
        - --log-level info
        command:
        - envoy
        env:
        - name: CONTOUR_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: ENVOY_POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        image: docker.io/envoyproxy/envoy:v1.31.3
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            httpGet:
              path: /shutdown
              port: 8090
              scheme: HTTP
        name: envoy
        ports:
        - containerPort: 8080
          hostPort: 80
          name: http
          protocol: TCP
        - containerPort: 8443
          hostPort: 443
          name: https
          protocol: TCP
        - containerPort: 8002
          hostPort: 8002
          name: metrics
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /ready
            port: 8002
            scheme: HTTP
          initialDelaySeconds: 3
          periodSeconds: 4
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /config
          name: envoy-config
          readOnly: true
        - mountPath: /certs
          name: envoycert
          readOnly: true
        - mountPath: /admin
          name: envoy-admin
      dnsPolicy: ClusterFirst
      initContainers:
      - args:
        - bootstrap
        - /config/envoy.json
        - --xds-address=contour
        - --xds-port=8001
        - --xds-resource-version=v3
        - --resources-dir=/config/resources
        - --envoy-cafile=/certs/ca.crt
        - --envoy-cert-file=/certs/tls.crt
        - --envoy-key-file=/certs/tls.key
        command:
        - contour
        env:
        - name: CONTOUR_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: ghcr.io/projectcontour/contour:v1.30.1
        imagePullPolicy: IfNotPresent
        name: envoy-initconfig
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /config
          name: envoy-config
        - mountPath: /certs
          name: envoycert
          readOnly: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsGroup: 65534
        runAsNonRoot: true
        runAsUser: 65534
      serviceAccount: envoy
      serviceAccountName: envoy
      terminationGracePeriodSeconds: 300
      volumes:
      - emptyDir: {}
        name: envoy-admin
      - emptyDir: {}
        name: envoy-config
      - name: envoycert
        secret:
          defaultMode: 420
          secretName: envoycert
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 10%
    type: RollingUpdate
status:
  currentNumberScheduled: 1
  desiredNumberScheduled: 1
  numberAvailable: 1
  numberMisscheduled: 0
  numberReady: 1
  observedGeneration: 1
  updatedNumberScheduled: 1
