apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"batch/v1","kind":"Job","metadata":{"annotations":{},"name":"contour-certgen-v1-30-1","namespace":"projectcontour"},"spec":{"backoffLimit":1,"completions":1,"parallelism":1,"template":{"metadata":{"labels":{"app":"contour-certgen"}},"spec":{"containers":[{"command":["contour","certgen","--kube","--incluster","--overwrite","--secrets-format=compact","--namespace=$(CONTOUR_NAMESPACE)"],"env":[{"name":"CONTOUR_NAMESPACE","valueFrom":{"fieldRef":{"fieldPath":"metadata.namespace"}}}],"image":"ghcr.io/projectcontour/contour:v1.30.1","imagePullPolicy":"IfNotPresent","name":"contour"}],"restartPolicy":"Never","securityContext":{"runAsGroup":65534,"runAsNonRoot":true,"runAsUser":65534},"serviceAccountName":"contour-certgen"}}}}
  creationTimestamp: "2024-11-25T18:52:52Z"
  generation: 1
  labels:
    app: contour-certgen
    batch.kubernetes.io/controller-uid: 6a6ee25d-6d6c-4b09-981c-af6ba2f5a8c8
    batch.kubernetes.io/job-name: contour-certgen-v1-30-1
    controller-uid: 6a6ee25d-6d6c-4b09-981c-af6ba2f5a8c8
    job-name: contour-certgen-v1-30-1
  name: contour-certgen-v1-30-1
  namespace: projectcontour
  resourceVersion: "134183"
  uid: 6a6ee25d-6d6c-4b09-981c-af6ba2f5a8c8
spec:
  backoffLimit: 1
  completionMode: NonIndexed
  completions: 1
  parallelism: 1
  selector:
    matchLabels:
      batch.kubernetes.io/controller-uid: 6a6ee25d-6d6c-4b09-981c-af6ba2f5a8c8
  suspend: false
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: contour-certgen
        batch.kubernetes.io/controller-uid: 6a6ee25d-6d6c-4b09-981c-af6ba2f5a8c8
        batch.kubernetes.io/job-name: contour-certgen-v1-30-1
        controller-uid: 6a6ee25d-6d6c-4b09-981c-af6ba2f5a8c8
        job-name: contour-certgen-v1-30-1
    spec:
      containers:
      - command:
        - contour
        - certgen
        - --kube
        - --incluster
        - --overwrite
        - --secrets-format=compact
        - --namespace=$(CONTOUR_NAMESPACE)
        env:
        - name: CONTOUR_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: ghcr.io/projectcontour/contour:v1.30.1
        imagePullPolicy: IfNotPresent
        name: contour
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext:
        runAsGroup: 65534
        runAsNonRoot: true
        runAsUser: 65534
      serviceAccount: contour-certgen
      serviceAccountName: contour-certgen
      terminationGracePeriodSeconds: 30
status:
  completionTime: "2024-11-25T18:53:03Z"
  conditions:
  - lastProbeTime: "2024-11-25T18:53:03Z"
    lastTransitionTime: "2024-11-25T18:53:03Z"
    status: "True"
    type: Complete
  ready: 0
  startTime: "2024-11-25T18:52:52Z"
  succeeded: 1
  uncountedTerminatedPods: {}
