apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"RoleBinding","metadata":{"annotations":{},"name":"contour","namespace":"projectcontour"},"roleRef":{"apiGroup":"rbac.authorization.k8s.io","kind":"Role","name":"contour-certgen"},"subjects":[{"kind":"ServiceAccount","name":"contour-certgen","namespace":"projectcontour"}]}
  creationTimestamp: "2024-11-25T18:52:52Z"
  name: contour
  namespace: projectcontour
  resourceVersion: "134063"
  uid: d9a49c1c-3db6-41b1-82b6-df44436486f8
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: contour-certgen
subjects:
- kind: ServiceAccount
  name: contour-certgen
  namespace: projectcontour
