apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"RoleBinding","metadata":{"annotations":{},"name":"contour-rolebinding","namespace":"projectcontour"},"roleRef":{"apiGroup":"rbac.authorization.k8s.io","kind":"Role","name":"contour"},"subjects":[{"kind":"ServiceAccount","name":"contour","namespace":"projectcontour"}]}
  creationTimestamp: "2024-11-25T18:52:52Z"
  name: contour-rolebinding
  namespace: projectcontour
  resourceVersion: "134069"
  uid: 3abceabe-6264-4834-8fd8-fb98b43af837
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: contour
subjects:
- kind: ServiceAccount
  name: contour
  namespace: projectcontour
