apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"name":"envoy","namespace":"projectcontour"}}
  creationTimestamp: "2024-11-25T18:52:51Z"
  name: envoy
  namespace: projectcontour
  resourceVersion: "134044"
  uid: c4cb0826-35d9-498b-b009-7a025a89961c
