apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"contour","namespace":"projectcontour"},"spec":{"ports":[{"name":"xds","port":8001,"protocol":"TCP","targetPort":8001}],"selector":{"app":"contour"},"type":"ClusterIP"}}
  creationTimestamp: "2024-11-25T18:52:52Z"
  name: contour
  namespace: projectcontour
  resourceVersion: "134078"
  uid: 780a3930-f266-4e3b-9344-5233164ccfb9
spec:
  clusterIP: 10.101.152.194
  clusterIPs:
  - 10.101.152.194
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: xds
    port: 8001
    protocol: TCP
    targetPort: 8001
  selector:
    app: contour
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
