apiVersion: v1
data:
  default.conf: |
    server { 
      listen 80;
      listen [::]:80;
      server_name localhost;
      location = /demo {
        root /usr/share/nginx/html;
        index demo.html; 
      }
      location / {
        root /usr/share/nginx/html;
        index index.html;
      }
      error_page   500 502 503 504  /50x.html;
      location = /50x.html {
        root   /usr/share/nginx/html;
      }
    }
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: default
