apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: main
      image: nginx:1.26.2
      volumeMounts:
        - name: config-volume
          mountPath: /etc/nginx/conf.d
        - name: html-volume
          mountPath: /usr/share/nginx/html/
  volumes:
    - name: config-volume
      configMap:
        name: nginx-config
    - name: html-volume
      configMap:
        name: nginx-html
  restartPolicy: Never
