apiVersion: v1
data:
  default.conf: |
    server { 
      listen 80;
      listen [::]:80;
      server_name localhost;
      location /demo {
        return 200 'hello world';
        add_header Content-Type text/plain;
      }
      error_page   500 502 503 504  /50x.html;
      location = /50x.html {
        root   /usr/share/nginx/html;
      }
    }
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: default
