apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: main
      image: docker.io/nginx:1.26.2
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP
      volumeMounts:
        - name: nginx-volume
          mountPath: /etc/nginx/
    - name: sidecar
      image: busybox
      command: ["/bin/sh", "-c", "sleep 3600"]
  volumes:
    - name: nginx-volume
      configMap:
        name: nginx-config
